# Generated by Django 5.2.4 on 2025-07-24 10:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.TextField(max_length=13)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('profile_pic', models.FileField(default='', upload_to='farmer_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='ratings',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
