# Generated by Django 5.2.4 on 2025-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0003_farmer_rename_ratings_feedback_rating_feedback_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.TextField(max_length=13)),
                ('product_pic', models.FileField(default='', upload_to='product_pic/')),
                ('product_status', models.CharField(default='available', max_length=100)),
            ],
        ),
    ]
