# Generated by Django 5.2.4 on 2025-07-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
