# Generated by Django 5.2.4 on 2025-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0005_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=13),
        ),
    ]
