# Generated by Django 5.2.4 on 2025-08-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0006_alter_product_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='agro_app.farmer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=13),
        ),
    ]
